;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
				c-electric-paren
				crux-move-beginning-of-line
				indent-for-tab-command
				))

(setq mc/cmds-to-run-once
      '(
				forward-sexp
				))
